# Materi List 2 Dimensi

In [1]:
matrik = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
print(matrik)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [2]:
matrik[1]

[5, 6, 7, 8]

In [3]:
matrik[1][2]
#pada perintah matrik 1 berarti pada baris matrik hitungan 1 lalu di perintahkan lagi dalam baris tersebut dicari matrik hitungan ke 2

7

In [4]:
matrik[1][2]=100
print(matrik[1][2])

100


In [5]:
matrik

[[1, 2, 3, 4], [5, 6, 100, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

Contoh Penerapan list 2 dimensi

In [6]:
for baris in matrik:
    print(baris)
    for kolom in baris:
        print(kolom)

[1, 2, 3, 4]
1
2
3
4
[5, 6, 100, 8]
5
6
100
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 16]
13
14
15
16


*Percobaan Materi List 2 Dimensi

In [7]:
matrik = [
    [7,22,24,26],
    [20,21,24,30],
    [10,9,14,2],
    [13,14,15,16]
]
print(matrik)

[[7, 22, 24, 26], [20, 21, 24, 30], [10, 9, 14, 2], [13, 14, 15, 16]]


In [8]:
matrik[2]
#Meminta matrik pada hitungan ke 2

[10, 9, 14, 2]

In [9]:
matrik [2][3]

2

In [10]:
matrik[2][3]=599
print(matrik[2][3])

599


In [11]:
matrik

[[7, 22, 24, 26], [20, 21, 24, 30], [10, 9, 14, 599], [13, 14, 15, 16]]

In [12]:
for baris in matrik:
    print(baris)
    for kolom in baris:
        print(kolom)

[7, 22, 24, 26]
7
22
24
26
[20, 21, 24, 30]
20
21
24
30
[10, 9, 14, 599]
10
9
14
599
[13, 14, 15, 16]
13
14
15
16


*Percobaan ke 2

In [13]:
nama_teman = [
    ['gunggek','wanda','marsanda','tya'],
    ['via','anya','sintya','doni'],
    ['diva','muti','surya','teguh'],
    ['gusde','nanda','gunggita','ayik']
]
print(matrik)
#kali ini output yang keluar adalah masukan data sebelum nya seharusnya di sesuaikan dengan nama teman

[[7, 22, 24, 26], [20, 21, 24, 30], [10, 9, 14, 599], [13, 14, 15, 16]]


In [14]:
nama_teman = [
    ['gunggek','wanda','marsanda','tya'],
    ['via','anya','sintya','doni'],
    ['diva','muti','surya','teguh'],
    ['gusde','nanda','gunggita','ayik']
]
print(nama_teman)

[['gunggek', 'wanda', 'marsanda', 'tya'], ['via', 'anya', 'sintya', 'doni'], ['diva', 'muti', 'surya', 'teguh'], ['gusde', 'nanda', 'gunggita', 'ayik']]


In [15]:
nama_teman[2]

['diva', 'muti', 'surya', 'teguh']

In [16]:
nama_teman[2][3]

'teguh'

In [17]:
for baris in nama_teman:
    print(baris)
    for kolom in baris:
        print(kolom)

['gunggek', 'wanda', 'marsanda', 'tya']
gunggek
wanda
marsanda
tya
['via', 'anya', 'sintya', 'doni']
via
anya
sintya
doni
['diva', 'muti', 'surya', 'teguh']
diva
muti
surya
teguh
['gusde', 'nanda', 'gunggita', 'ayik']
gusde
nanda
gunggita
ayik


# Materi Tuples

In [18]:
angka = (0,1,1,3,4,5,5)

In [19]:
print(angka[0])

0


In [20]:
print(angka[0:3])

(0, 1, 1)


In [21]:
for isi in angka[0:3]:
    print(isi)

0
1
1


In [23]:
angka[0] = 10

TypeError: 'tuple' object does not support item assignment

In [24]:
angka.append(10)

AttributeError: 'tuple' object has no attribute 'append'

In [25]:
angka.remove(5)

AttributeError: 'tuple' object has no attribute 'remove'

In [26]:
angka.count(5)
#pada perintah kali ini bermaksud menghitung berapa jumlah angka 5

2

In [27]:
angka.index(4)

4

*Percobaan materi Tuples

In [28]:
angka_lahir = (13,20,21,24,20,30)

In [29]:
print(angka[20])
#output nya error dikarenakan tidak ada data ke 20 karena hitungan data hanya sampai ke 5

IndexError: tuple index out of range

In [30]:
print(angka_lahir[2])

21


In [31]:
print(angka_lahir[0:3])

(13, 20, 21)


In [32]:
for isi in angka_lahir[0:3]:
    print(isi)

13
20
21


In [33]:
angka_lahir.count(20)

2

In [34]:
angka.index(20)
#output nya error dikarenakan pada perintah di lengkapi yang seharusnya angka_lahir.index(20)

ValueError: tuple.index(x): x not in tuple

In [35]:
angka_lahir.index(20)

1

# Materi Dictionaries

In [36]:
data_orang = {
    "nama" : "Ketut Dogler",
    "umur" : 12,
    "apakah_singel" : False
}

In [37]:
print(data_orang['nama'])

Ketut Dogler


In [38]:
print(data_orang['Nama'])

KeyError: 'Nama'

In [39]:
print(data_orang.get('nama'))

Ketut Dogler


In [40]:
print(data_orang.get('Nama'))

None


In [41]:
print(data_orang.get('tanggal_lahir'))

None


In [42]:
print(data_orang.get('tanggal_lahir','2-2-2010'))

2-2-2010


In [43]:
print(data_orang)

{'nama': 'Ketut Dogler', 'umur': 12, 'apakah_singel': False}


In [44]:
print(data_orang["tanggal_lahir"])

KeyError: 'tanggal_lahir'

In [45]:
data_orang['Hp'] = '08123456789'

In [46]:
print(data_orang["Hp"])

KeyError: 'HP'

In [47]:
print(data_orang)

{'nama': 'Ketut Dogler', 'umur': 12, 'apakah_singel': False, 'Hp': '08123456789'}


*Percobaan materi Dictionaries

In [1]:
data_tya = {
    "Nama" : "Ni Putu Karistya Paicha Maesi",
    "Umur" : 19,
    "Apakah_singel" : True
}

In [2]:
print(data_tya['Nama'])

Ni Putu Karistya Paicha Maesi


In [3]:
print(data_tya['nama'])

KeyError: 'nama'

In [4]:
print(data_tya.get('Nama'))

Ni Putu Karistya Paicha Maesi


In [5]:
print(data_tya.get('nama'))

None


In [6]:
print(data_tya.get('tanggal_lahir'))

None


In [7]:
print(data_tya.get('tanggal_lahir', '13-08-2004'))

13-08-2004


In [8]:
print(data_tya)

{'Nama': 'Ni Putu Karistya Paicha Maesi', 'Umur': 19, 'Apakah_singel': True}


In [9]:
print(data_tya["tanggal_lahir"])

KeyError: 'tanggal_lahir'

In [10]:
data_tya['HP'] = 'ciee kepo'

In [11]:
print(data_tya["HP"])

ciee kepo


In [12]:
print(data_tya)

{'Nama': 'Ni Putu Karistya Paicha Maesi', 'Umur': 19, 'Apakah_singel': True, 'HP': 'ciee kepo'}


# Materi Fungsi Dalam Python

In [13]:
def full_nama(first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")

In [14]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_nama(first_name,last_name)

Nama depan anda adalah Ni Putu
Nama belakang anda adalah Karistya Paicha maesi
Nama lengkapnya adalah Ni Putu Karistya Paicha maesi


Tugas Fungsi pada Python

In [15]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [16]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [17]:
waktu_sampai(80,60)

1.3333333333333333


In [18]:
waktu_tempuh(80,60)

1.3333333333333333

In [13]:
a = waktu_sampai(80,60)
print(a)

1.3333333333333333
None


In [20]:
b = waktu_tempuh(80,60)
print(b)

1.3333333333333333


In [1]:
import numpy as np

In [2]:
def luas_segitiga(alas,tinggi):
    luas = (1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari):
    luas = np.pi*(jari_jari**2)
    return luas
def luas_persegi(sisi):
    luas = sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return luas

In [3]:
jenis_bidang = input("Tulis jenis bidangnya ")
if jenis_bidang.upper() == 'SEGITIGA' :
    alas = float(input('Berapakah panjang alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'LINGKARAN':
    jari_jari = float(input('Berapakah panjang jari-jarinya? '))
    luas = luas_lingkaran(jari_jari)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif (jenis_bidang.upper() == 'PERSEGI') or (jenis_bidang.upper() =='BUJUR SANGKAR'):
    sisi = float(input('Berapakah sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
    panjang = float(input('Berapakah panjangnya? '))
    lebar = float(input('Berapakah lebarnya? '))
    luas = luas_persegi_panjang(panjang,lebar)
    print(f"Luas {jenis_bidang} adalah {luas}")
else:
    print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak ada.")
    print("Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI, PERSEGI PANJANG.")
    print('Terimakasih')


Tulis jenis bidangnya LINGKARAN
Berapakah panjang jari-jarinya? 7
Luas LINGKARAN adalah 153.93804002589985


Percobaan Materi Tugas Fungsi pada Python

In [3]:
def full_nama(first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")
def tempat_tanggal_lahir(tempat_lahir,tanggal_lahir):
    print(f"Lahir di {tempat_lahir} {tanggal_lahir}")
#mencoba mendefinisikan 2 hal yang berbeda

In [4]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_nama(first_name,last_name)
tanggal_lahir = input("Tanggal lahir anda adalah ")
tempat_lahir = input("Tempat lahir anda dimana ")
tempat_tanggal_lahir(tempat_lahir,tanggal_lahir)

Nama depan anda adalah putu
Nama belakang anda adalah tya
Nama lengkapnya adalah putu tya
Tanggal lahir anda adalah 13 agustus
Tempat lahir anda dimana denpasar
Lahir di denpasar 13 agustus


In [5]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [9]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [10]:
waktu_sampai(100,50)

2.0


In [11]:
waktu_tempuh(100,50)

2.0

In [12]:
a = waktu_sampai(100,50)
print(a)

2.0
None


In [14]:
b = waktu_tempuh(100,50)
print(b)

2.0


In [4]:
import numpy as np

In [5]:
def luas_segitiga(alas,tinggi):
    luas = (1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari):
    luas = np.pi*(jari_jari**2)
    return luas
def luas_persegi(sisi):
    luas = sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return luas
def luas_layang_layang(digonal1,diagonal2):
    luas = (1/2)*diagonal1*diagonal2
    return luas
def luas_jajar_genjang(alas,tinggi):
    luas = alas*tinggi
    return luas 
#mencoba menambahkan rumus

In [9]:
jenis_bidang = input("Tulis jenis bidangnya ")
if jenis_bidang.upper() == 'SEGITIGA' :
    alas = float(input('Berapakah panjang alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'LINGKARAN':
    jari_jari = float(input('Berapakah panjang jari-jarinya? '))
    luas = luas_lingkaran(jari_jari)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif (jenis_bidang.upper() == 'PERSEGI') or (jenis_bidang.upper() =='BUJUR SANGKAR'):
    sisi = float(input('Berapakah sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
    panjang = float(input('Berapakah panjangnya? '))
    lebar = float(input('Berapakah lebarnya? '))
    luas = luas_persegi_panjang(panjang,lebar)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'LAYANG LAYANG':
    diagonal1 = float(input('Berapakah panjang diagonal1? '))
    diagonal2 = float(input('Berapakah panjang diagonal2? '))
    luas = luas_layang_layang(diagonal1,diagonal2)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'JAJAR GENJANG':
    alas = float(input('Berapakah alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_jajar_genjang(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
else:
    print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak ada.")
    print("Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI, PERSEGI PANJANG, LAYANG LAYANG,JAJAR GENJANG.")
    print('Terimakasih')

Tulis jenis bidangnya LAYANG LAYANG
Berapakah panjang diagonal1? 10
Berapakah panjang diagonal2? 14
Luas LAYANG LAYANG adalah 70.0


# Materi Numpy

In [10]:
import pandas as pd

# Perintah Dasar pada Numpy

In [11]:
a = np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [12]:
b = np.array([[5,6,7,8],[9,8,7,6]])
print(b)

[[5 6 7 8]
 [9 8 7 6]]


In [13]:
c = np.array([[[0,1,2,3],[4,5,6,7]],[[8,9,8,7],[6,5,4,3]],[[1,2,3,4],[5,6,7,8]]])
print(c)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [14]:
a.ndim
#disini ditanya berapakah ada kolom pada a

1

In [15]:
b.ndim
#disini juga di tanya berapa ada kolom pada b

2

In [16]:
c.ndim

3

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
c.shape

Percobaan Perintah Dasar pada Numpy

In [ ]:
a = np.array([10,11,12,13])
print(a)

In [ ]:
b = np.array([[14,15,16,17],[13,15,17,19]])
print(b)

In [ ]:
c = np.array([[[10,11,12,13],[14,15,16,17]],[[13,15,17,19],[16,15,14,13]],[[11,12,13,14],[15,16,17,18]]])
print(c)

In [ ]:
a.ndim

In [ ]:
b.ndim

In [ ]:
c.ndim

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
c.shape

# Memanggil Anggota,Kolom dan Baris dengan Numpy

In [ ]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d)

In [ ]:
d[0,3]

In [ ]:
d[1,:]

In [ ]:
d[:,2]

In [ ]:
d[0,1:3]

In [ ]:
d[0,0:3:2]

In [ ]:
d[0,0] = 100
print(d)

Percobaan saat Memanggil Anggota,Kolom dan baris dengan Numpy

In [ ]:
d = np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
print(d)

In [ ]:
d[1,2]
#dimulai dari hitungan kolom ke 1 dicari hitungan anggota ke 2

In [ ]:
d[2,:]
#dimulai dari hitungan kolom ke 2

In [ ]:
d[:,3]
#perintah ini memerintahkan untuk mengambil hitungan anggota ke 3 pada masing-masing kolom

In [ ]:
d[1,1:3]
#perintah pada kolom ke 1 lalu di ambil hitungan pada kolom tersebut pada anggota ke 1 dengan batasan ke 3

In [ ]:
d[1,1:3:2]

In [ ]:
d[1,1] = 200
print(d)
#diperintahkan untuk menambah angka 200 pada kolom hitungan ke 1 dan anggota ke 1

# Matrix pada Numpy

In [ ]:
np.ones((2,3))

In [ ]:
np.zeros((3,2))

In [ ]:
np.identity(4)

In [ ]:
np.ones((2,3,4))

In [ ]:
np.full((3,2),9)

In [ ]:
np.random.rand(4,3)

In [ ]:
np.random.randint(1,10,size=(3,4))

In [ ]:
a = np.zeros((10,10))
print(a)

In [ ]:
b = np.identity(10)
print(b)

In [ ]:
c = 9*b
print(c)

In [ ]:
d = np.ones((8,8))
e = np.identity(8)*8
f = d+e
print(f)

In [ ]:
c[1:-1,1:-1] = f
print(c)

In [ ]:
g = np.identity(6)*9
c[2:-2,2:-2] = g
print(c)

In [ ]:
h = np.ones((4,4))*2
i = np.identity(4) * 7
j = h + i
print(j)

In [ ]:
c[3:-3,3;-3] = j
print(c)

In [ ]:
k = np.identity(2)*9
c[4:-4,4:-4] = k
print(c)

# Copy pada Numpy

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

In [ ]:
b = a
print(b)

In [ ]:
b[0] = 10
print(b)

In [ ]:
print(a)

In [ ]:
c = np.array([1,2,3,4,5])
print(c)

In [ ]:
d = c.copy()
print(d)

In [ ]:
d[0] = 10
print(d)

In [ ]:
print(c)

# Operasi Matematika pada Numpy

In [ ]:
a+2

In [ ]:
a-2

In [ ]:
a*2

In [ ]:
a/2

In [ ]:
a**2

In [ ]:
b = np.array([6,7,8,9,10])
print(b)

In [ ]:
b = np.array([6,7,8,9,10])
print(b)

In [ ]:
a+b

In [ ]:
a-b

In [ ]:
a*b

In [ ]:
a/b

In [ ]:
b**a

In [ ]:
np.cos(a)

In [ ]:
np.cos(a)

In [ ]:
np.tan(a)

In [ ]:
np.sinh(a)

In [ ]:
np.cosh(a)

In [ ]:
np.tanh(a)

In [ ]:
np.sqrt(a)

# Perkalian Matrik pada Numpy

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

In [ ]:
b = np.array([[9,10,11,12],[13,1,4,15,16]])
print(b)

In [ ]:
c = a*b
print(c)

In [ ]:
d = np.matmul(a,b)

In [ ]:
e = np.array([[9,10],[11,12],[13,14],[15,16]])
print(e)

In [ ]:
f = np.matmul(a,e)
print(f)

In [ ]:
g = a*e

# Min,Max dan Sum pada Numpy

In [ ]:
a = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print(a)

In [ ]:
b = np.min(a)
print(b)

In [ ]:
c = np.min(a,axis=0)
print(c)

In [ ]:
d = np.min(a,axis=1)
print(d)

In [ ]:
e = np.max(a)
print(e)

In [ ]:
f = np.max(a,axis=0)
print(f)

In [ ]:
g = np.max(a,axis=1)
print(g)

In [ ]:
h = np.sum(a)
print(h)

In [ ]:
h = np.sum(a,axis=0)
print(h)

In [ ]:
i = np.sum(a,axis=1)
print(i)