# Materi List 2 Dimensi

In [1]:
matrik = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
print(matrik)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [2]:
matrik[1]

[5, 6, 7, 8]

In [3]:
matrik[1][2]
#pada perintah matrik 1 berarti pada baris matrik hitungan 1 lalu di perintahkan lagi dalam baris tersebut dicari matrik hitungan ke 2

7

In [4]:
matrik[1][2]=100
print(matrik[1][2])

100


In [5]:
matrik

[[1, 2, 3, 4], [5, 6, 100, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

Contoh Penerapan list 2 dimensi

In [6]:
for baris in matrik:
    print(baris)
    for kolom in baris:
        print(kolom)

[1, 2, 3, 4]
1
2
3
4
[5, 6, 100, 8]
5
6
100
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 16]
13
14
15
16


*Percobaan Materi List 2 Dimensi

In [7]:
matrik = [
    [7,22,24,26],
    [20,21,24,30],
    [10,9,14,2],
    [13,14,15,16]
]
print(matrik)

[[7, 22, 24, 26], [20, 21, 24, 30], [10, 9, 14, 2], [13, 14, 15, 16]]


In [8]:
matrik[2]
#Meminta matrik pada hitungan ke 2

[10, 9, 14, 2]

In [9]:
matrik [2][3]

2

In [10]:
matrik[2][3]=599
print(matrik[2][3])

599


In [11]:
matrik

[[7, 22, 24, 26], [20, 21, 24, 30], [10, 9, 14, 599], [13, 14, 15, 16]]

In [12]:
for baris in matrik:
    print(baris)
    for kolom in baris:
        print(kolom)

[7, 22, 24, 26]
7
22
24
26
[20, 21, 24, 30]
20
21
24
30
[10, 9, 14, 599]
10
9
14
599
[13, 14, 15, 16]
13
14
15
16


*Percobaan ke 2

In [13]:
nama_teman = [
    ['gunggek','wanda','marsanda','tya'],
    ['via','anya','sintya','doni'],
    ['diva','muti','surya','teguh'],
    ['gusde','nanda','gunggita','ayik']
]
print(matrik)
#kali ini output yang keluar adalah masukan data sebelum nya seharusnya di sesuaikan dengan nama teman

[[7, 22, 24, 26], [20, 21, 24, 30], [10, 9, 14, 599], [13, 14, 15, 16]]


In [14]:
nama_teman = [
    ['gunggek','wanda','marsanda','tya'],
    ['via','anya','sintya','doni'],
    ['diva','muti','surya','teguh'],
    ['gusde','nanda','gunggita','ayik']
]
print(nama_teman)

[['gunggek', 'wanda', 'marsanda', 'tya'], ['via', 'anya', 'sintya', 'doni'], ['diva', 'muti', 'surya', 'teguh'], ['gusde', 'nanda', 'gunggita', 'ayik']]


In [15]:
nama_teman[2]

['diva', 'muti', 'surya', 'teguh']

In [16]:
nama_teman[2][3]

'teguh'

In [17]:
for baris in nama_teman:
    print(baris)
    for kolom in baris:
        print(kolom)

['gunggek', 'wanda', 'marsanda', 'tya']
gunggek
wanda
marsanda
tya
['via', 'anya', 'sintya', 'doni']
via
anya
sintya
doni
['diva', 'muti', 'surya', 'teguh']
diva
muti
surya
teguh
['gusde', 'nanda', 'gunggita', 'ayik']
gusde
nanda
gunggita
ayik


# Materi Tuples

In [18]:
angka = (0,1,1,3,4,5,5)

In [19]:
print(angka[0])

0


In [20]:
print(angka[0:3])

(0, 1, 1)


In [21]:
for isi in angka[0:3]:
    print(isi)

0
1
1


In [22]:
angka[0] = 10

TypeError: 'tuple' object does not support item assignment

In [23]:
angka.append(10)

AttributeError: 'tuple' object has no attribute 'append'

In [24]:
angka.remove(5)

AttributeError: 'tuple' object has no attribute 'remove'

In [25]:
angka.count(5)
#pada perintah kali ini bermaksud menghitung berapa jumlah angka 5

2

In [26]:
angka.index(4)

4

*Percobaan materi Tuples

In [27]:
angka_lahir = (13,20,21,24,20,30)

In [28]:
print(angka[20])
#output nya error dikarenakan tidak ada data ke 20 karena hitungan data hanya sampai ke 5

IndexError: tuple index out of range

In [29]:
print(angka_lahir[2])

21


In [30]:
print(angka_lahir[0:3])

(13, 20, 21)


In [31]:
for isi in angka_lahir[0:3]:
    print(isi)

13
20
21


In [32]:
angka_lahir.count(20)

2

In [33]:
angka.index(20)
#output nya error dikarenakan pada perintah di lengkapi yang seharusnya angka_lahir.index(20)

ValueError: tuple.index(x): x not in tuple

In [34]:
angka_lahir.index(20)

1

# Materi Dictionaries

In [35]:
data_orang = {
    "nama" : "Ketut Dogler",
    "umur" : 12,
    "apakah_singel" : False
}

In [36]:
print(data_orang['nama'])

Ketut Dogler


In [37]:
print(data_orang['Nama'])

KeyError: 'Nama'

In [38]:
print(data_orang.get('nama'))

Ketut Dogler


In [39]:
print(data_orang.get('Nama'))

None


In [40]:
print(data_orang.get('tanggal_lahir'))

None


In [41]:
print(data_orang.get('tanggal_lahir','2-2-2010'))

2-2-2010


In [42]:
print(data_orang)

{'nama': 'Ketut Dogler', 'umur': 12, 'apakah_singel': False}


In [43]:
print(data_orang["tanggal_lahir"])

KeyError: 'tanggal_lahir'

In [44]:
data_orang['Hp'] = '08123456789'

In [45]:
print(data_orang["Hp"])

08123456789


In [46]:
print(data_orang)

{'nama': 'Ketut Dogler', 'umur': 12, 'apakah_singel': False, 'Hp': '08123456789'}


*Percobaan materi Dictionaries

In [47]:
data_tya = {
    "Nama" : "Ni Putu Karistya Paicha Maesi",
    "Umur" : 19,
    "Apakah_singel" : True
}

In [48]:
print(data_tya['Nama'])

Ni Putu Karistya Paicha Maesi


In [49]:
print(data_tya['nama'])

KeyError: 'nama'

In [50]:
print(data_tya.get('Nama'))

Ni Putu Karistya Paicha Maesi


In [51]:
print(data_tya.get('nama'))

None


In [52]:
print(data_tya.get('tanggal_lahir'))

None


In [53]:
print(data_tya.get('tanggal_lahir', '13-08-2004'))

13-08-2004


In [54]:
print(data_tya)

{'Nama': 'Ni Putu Karistya Paicha Maesi', 'Umur': 19, 'Apakah_singel': True}


In [55]:
print(data_tya["tanggal_lahir"])

KeyError: 'tanggal_lahir'

In [56]:
data_tya['HP'] = 'ciee kepo'

In [57]:
print(data_tya["HP"])

ciee kepo


In [58]:
print(data_tya)

{'Nama': 'Ni Putu Karistya Paicha Maesi', 'Umur': 19, 'Apakah_singel': True, 'HP': 'ciee kepo'}


# Materi Fungsi Dalam Python

In [59]:
def full_nama(first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")

In [60]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_nama(first_name,last_name)

Nama depan anda adalah putu
Nama belakang anda adalah tya
Nama lengkapnya adalah putu tya


Tugas Fungsi pada Python

In [61]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [62]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [63]:
waktu_sampai(80,60)

1.3333333333333333


In [64]:
waktu_tempuh(80,60)

1.3333333333333333

In [65]:
a = waktu_sampai(80,60)
print(a)

1.3333333333333333
None


In [66]:
b = waktu_tempuh(80,60)
print(b)

1.3333333333333333


In [67]:
import numpy as np

In [68]:
def luas_segitiga(alas,tinggi):
    luas = (1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari):
    luas = np.pi*(jari_jari**2)
    return luas
def luas_persegi(sisi):
    luas = sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return luas

In [69]:
jenis_bidang = input("Tulis jenis bidangnya ")
if jenis_bidang.upper() == 'SEGITIGA' :
    alas = float(input('Berapakah panjang alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'LINGKARAN':
    jari_jari = float(input('Berapakah panjang jari-jarinya? '))
    luas = luas_lingkaran(jari_jari)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif (jenis_bidang.upper() == 'PERSEGI') or (jenis_bidang.upper() =='BUJUR SANGKAR'):
    sisi = float(input('Berapakah sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
    panjang = float(input('Berapakah panjangnya? '))
    lebar = float(input('Berapakah lebarnya? '))
    luas = luas_persegi_panjang(panjang,lebar)
    print(f"Luas {jenis_bidang} adalah {luas}")
else:
    print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak ada.")
    print("Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI, PERSEGI PANJANG.")
    print('Terimakasih')


Tulis jenis bidangnya LAYANG LAYANG
Maaf bidang LAYANG LAYANG yang anda masukkan tidak ada.
Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI, PERSEGI PANJANG.
Terimakasih


Percobaan Materi Tugas Fungsi pada Python

In [70]:
def full_nama(first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")
def tempat_tanggal_lahir(tempat_lahir,tanggal_lahir):
    print(f"Lahir di {tempat_lahir} {tanggal_lahir}")
#mencoba mendefinisikan 2 hal yang berbeda

In [71]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_nama(first_name,last_name)
tanggal_lahir = input("Tanggal lahir anda adalah ")
tempat_lahir = input("Tempat lahir anda dimana ")
tempat_tanggal_lahir(tempat_lahir,tanggal_lahir)

Nama depan anda adalah PUTU
Nama belakang anda adalah TYA
Nama lengkapnya adalah PUTU TYA
Tanggal lahir anda adalah 13 agustus
Tempat lahir anda dimana denpasar
Lahir di denpasar 13 agustus


In [72]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [73]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [74]:
waktu_sampai(100,50)

2.0


In [75]:
waktu_tempuh(100,50)

2.0

In [76]:
a = waktu_sampai(100,50)
print(a)

2.0
None


In [77]:
b = waktu_tempuh(100,50)
print(b)

2.0


In [78]:
import numpy as np

In [79]:
def luas_segitiga(alas,tinggi):
    luas = (1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari):
    luas = np.pi*(jari_jari**2)
    return luas
def luas_persegi(sisi):
    luas = sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return luas
def luas_layang_layang(digonal1,diagonal2):
    luas = (1/2)*diagonal1*diagonal2
    return luas
def luas_jajar_genjang(alas,tinggi):
    luas = alas*tinggi
    return luas 
#mencoba menambahkan rumus

In [81]:
jenis_bidang = input("Tulis jenis bidangnya ")
if jenis_bidang.upper() == 'SEGITIGA' :
    alas = float(input('Berapakah panjang alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'LINGKARAN':
    jari_jari = float(input('Berapakah panjang jari-jarinya? '))
    luas = luas_lingkaran(jari_jari)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif (jenis_bidang.upper() == 'PERSEGI') or (jenis_bidang.upper() =='BUJUR SANGKAR'):
    sisi = float(input('Berapakah sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
    panjang = float(input('Berapakah panjangnya? '))
    lebar = float(input('Berapakah lebarnya? '))
    luas = luas_persegi_panjang(panjang,lebar)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'LAYANG LAYANG':
    diagonal1 = float(input('Berapakah panjang diagonal1? '))
    diagonal2 = float(input('Berapakah panjang diagonal2? '))
    luas = luas_layang_layang(diagonal1,diagonal2)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'JAJAR GENJANG':
    alas = float(input('Berapakah alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_jajar_genjang(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
else:
    print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak ada.")
    print("Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI, PERSEGI PANJANG, LAYANG LAYANG,JAJAR GENJANG.")
    print('Terimakasih')

Tulis jenis bidangnya LAYANG LAYANG
Berapakah panjang diagonal1? 12
Berapakah panjang diagonal2? 10
Luas LAYANG LAYANG adalah 60.0


# Materi Numpy

In [82]:
import pandas as pd

# Perintah Dasar pada Numpy

In [83]:
a = np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [84]:
b = np.array([[5,6,7,8],[9,8,7,6]])
print(b)

[[5 6 7 8]
 [9 8 7 6]]


In [85]:
c = np.array([[[0,1,2,3],[4,5,6,7]],[[8,9,8,7],[6,5,4,3]],[[1,2,3,4],[5,6,7,8]]])
print(c)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [86]:
a.ndim
#disini ditanya berapakah ada kolom pada a

1

In [87]:
b.ndim
#disini juga di tanya berapa ada kolom pada b

2

In [88]:
c.ndim

3

In [89]:
a.shape

(5,)

In [90]:
b.shape

(2, 4)

In [91]:
c.shape

(3, 2, 4)

Percobaan Perintah Dasar pada Numpy

In [92]:
a = np.array([10,11,12,13])
print(a)

[10 11 12 13]


In [93]:
b = np.array([[14,15,16,17],[13,15,17,19]])
print(b)

[[14 15 16 17]
 [13 15 17 19]]


In [94]:
c = np.array([[[10,11,12,13],[14,15,16,17]],[[13,15,17,19],[16,15,14,13]],[[11,12,13,14],[15,16,17,18]]])
print(c)

[[[10 11 12 13]
  [14 15 16 17]]

 [[13 15 17 19]
  [16 15 14 13]]

 [[11 12 13 14]
  [15 16 17 18]]]


In [95]:
a.ndim

1

In [96]:
b.ndim

2

In [97]:
c.ndim

3

In [98]:
a.shape

(4,)

In [99]:
b.shape

(2, 4)

In [100]:
c.shape

(3, 2, 4)

# Memanggil Anggota,Kolom dan Baris dengan Numpy

In [101]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [102]:
d[0,3]

4

In [103]:
d[1,:]

array([5, 6, 7, 8])

In [104]:
d[:,2]

array([ 3,  7, 11])

In [105]:
d[0,1:3]

array([2, 3])

In [106]:
d[0,0:3:2]

array([1, 3])

In [107]:
d[0,0] = 100
print(d)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


Percobaan saat Memanggil Anggota,Kolom dan baris dengan Numpy

In [108]:
d = np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
print(d)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [109]:
d[1,2]
#dimulai dari hitungan kolom ke 1 dicari hitungan anggota ke 2

17

In [110]:
d[2,:]
#dimulai dari hitungan kolom ke 2

array([19, 20, 21, 22])

In [111]:
d[:,3]
#perintah ini memerintahkan untuk mengambil hitungan anggota ke 3 pada masing-masing kolom

array([14, 18, 22])

In [112]:
d[1,1:3]
#perintah pada kolom ke 1 lalu di ambil hitungan pada kolom tersebut pada anggota ke 1 dengan batasan ke 3

array([16, 17])

In [113]:
d[1,1:3:2]

array([16])

In [114]:
d[1,1] = 200
print(d)
#diperintahkan untuk menambah angka 200 pada kolom hitungan ke 1 dan anggota ke 1

[[ 11  12  13  14]
 [ 15 200  17  18]
 [ 19  20  21  22]]


# Matrix pada Numpy

In [115]:
np.ones((2,3))
#diperintahkan bahwa untuk 2 baris dan masing' baris tersebut memuat 3 kolom sehingga membentuk matrik dan nilai yang diberi adalah 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [116]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [117]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [118]:
np.ones((2,3,4))
#sama seperti diatas namun disini dibuat 2 kolom dengan masing" 3 baris lalu setiap baris memuat 4 anggota

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [119]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [120]:
np.random.rand(4,3)
#diambil sembarang angka dengan ukuran matriks 4 baris dan 3 kolom

array([[0.66498303, 0.57908404, 0.38362409],
       [0.72651986, 0.27740627, 0.85214577],
       [0.99207371, 0.4432453 , 0.82494337],
       [0.05274586, 0.2609244 , 0.32738033]])

In [121]:
np.random.randint(1,10,size=(3,4))

array([[7, 6, 7, 7],
       [6, 9, 9, 9],
       [4, 1, 9, 3]])

In [122]:
a = np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [123]:
b = np.identity(10)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [124]:
c = 9*b
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [125]:
d = np.ones((8,8))
e = np.identity(8)*8
f = d+e
print(f)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [126]:
c[1:-1,1:-1] = f
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [127]:
g = np.identity(6)*9
c[2:-2,2:-2] = g
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [128]:
h = np.ones((4,4))*2
i = np.identity(4) * 7
j = h + i
print(j)

[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


In [129]:
c[3:-3,3;-3] = j
print(c)

SyntaxError: invalid syntax (2993326777.py, line 1)

In [130]:
k = np.identity(2)*9
c[4:-4,4:-4] = k
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


# Copy pada Numpy

In [131]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [132]:
b = a
print(b)

[1 2 3 4 5]


In [133]:
b[0] = 10
print(b)

[10  2  3  4  5]


In [134]:
print(a)

[10  2  3  4  5]


In [135]:
c = np.array([1,2,3,4,5])
print(c)

[1 2 3 4 5]


In [136]:
d = c.copy()
print(d)

[1 2 3 4 5]


In [137]:
d[0] = 10
print(d)

[10  2  3  4  5]


In [138]:
print(c)

[1 2 3 4 5]


# Operasi Matematika pada Numpy

In [139]:
a+2
#sebelumnya didefinisikan nilai a lalu pada masing masing variable a di tambah 2

array([12,  4,  5,  6,  7])

In [140]:
a-2

array([8, 0, 1, 2, 3])

In [141]:
a*2

array([20,  4,  6,  8, 10])

In [142]:
a/2

array([5. , 1. , 1.5, 2. , 2.5])

In [143]:
a**2

array([100,   4,   9,  16,  25], dtype=int32)

In [144]:
b = np.array([6,7,8,9,10])
print(b)

[ 6  7  8  9 10]


In [145]:
b = np.array([6,7,8,9,10])
print(b)

[ 6  7  8  9 10]


In [146]:
a+b
#tahap ini menjumlahkan 2 elemen yaitu elemen a dan b

array([16,  9, 11, 13, 15])

In [147]:
a-b

array([ 4, -5, -5, -5, -5])

In [148]:
a*b

array([60, 14, 24, 36, 50])

In [149]:
a/b

array([1.66666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [150]:
b**a

array([60466176,       49,      512,     6561,   100000], dtype=int32)

Operasi Matematika Trigonometri pada Numpy

In [151]:
np.cos(a)

array([-0.83907153, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [152]:
np.cos(a)

array([-0.83907153, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [153]:
np.tan(a)

array([ 0.64836083, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [154]:
np.sinh(a)

array([1.10132329e+04, 3.62686041e+00, 1.00178749e+01, 2.72899172e+01,
       7.42032106e+01])

In [155]:
np.cosh(a)

array([1.10132329e+04, 3.76219569e+00, 1.00676620e+01, 2.73082328e+01,
       7.42099485e+01])

In [156]:
np.tanh(a)

array([1.        , 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [157]:
np.sqrt(a)

array([3.16227766, 1.41421356, 1.73205081, 2.        , 2.23606798])

# Perkalian Matrik pada Numpy

In [178]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [179]:
b = np.array([[9,10,11,12],[13,14,15,16]])
print(b)

[[ 9 10 11 12]
 [13 14 15 16]]


In [180]:
c = a*b
print(c)

[[  9  20  33  48]
 [ 65  84 105 128]]


In [181]:
d = np.matmul(a,b)
#perkalian ini tidak memenuhi syarat dikarenakan ukuran matriks nya tidak berbeda

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [182]:
e = np.array([[9,10],[11,12],[13,14],[15,16]])
print(e)

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [183]:
f = np.matmul(a,e)
print(f)

[[130 140]
 [322 348]]


In [184]:
g = a*e
#perkalian matriks biasa ini tidak bisa jalan karena ukuran matriks a dan e berbeda

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

# Min,Max dan Sum pada Numpy

In [164]:
a = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [165]:
b = np.min(a)
print(b)

1


In [166]:
c = np.min(a,axis=0)
print(c)

[1 2 3 4]


In [167]:
d = np.min(a,axis=1)
print(d)

[1 5 9]


In [168]:
e = np.max(a)
print(e)

12


In [169]:
f = np.max(a,axis=0)
print(f)

[ 9 10 11 12]


In [170]:
g = np.max(a,axis=1)
print(g)

[ 4  8 12]


In [171]:
h = np.sum(a)
print(h)

78


In [172]:
h = np.sum(a,axis=0)
print(h)

[15 18 21 24]


In [173]:
i = np.sum(a,axis=1)
print(i)

[10 26 42]
